import SwiftUI

// MARK: - Advanced Options View

/// Dedicated view for expanded yt-dlp advanced options.
/// Writes CLI arguments to a Binding<[String]> consumed by NewDownloadView.
struct AdvancedOptionsView: View {
    @Binding var args: [String]

    // MARK: Subtitles
    @State private var downloadSubtitles = false
    @State private var autoGeneratedSubs = true
    @State private var subtitleLanguage = "en"
    @State private var subtitleFormat = SubtitleFormat.srt
    @State private var writeSeparateSubtitles = false
    @State private var embedSubtitles = true

    // MARK: Post-Processing
    @State private var embedThumbnail = true
    @State private var embedMetadata = true
    @State private var sponsorBlock = false
    @State private var remuxToMP4 = false
    @State private var extractAudio = false
    @State private var audioFormat = AudioFormat.mp3
    @State private var audioQuality = 0
    @State private var splitByChapters = false

    // MARK: Network
    @State private var proxyURL = ""
    @State private var sourceAddress = ""
    @State private var geoBypass = false

    // MARK: Authentication
    @State private var cookiesBrowser = CookiesBrowser.none
    @State private var username = ""
    @State private var password = ""

    // MARK: Output
    @State private var outputTemplate = "%(title)s.%(ext)s"
    @State private var speedLimit = ""
    @State private var noOverwrites = false
    @State private var writeInfoJSON = false
    @State private var writeThumbnail = false

    var body: some View {
        VStack(alignment: .leading, spacing: Design.Spacing.md) {
            subtitlesSection
            Divider()
            postProcessingSection
            Divider()
            networkSection
            Divider()
            authenticationSection
            Divider()
            outputSection
        }
        .padding(.top, Design.Spacing.sm)
        .modifier(SubtitleChangeWatcher(
            downloadSubtitles: downloadSubtitles,
            autoGeneratedSubs: autoGeneratedSubs,
            subtitleLanguage: subtitleLanguage,
            subtitleFormat: subtitleFormat,
            writeSeparateSubtitles: writeSeparateSubtitles,
            embedSubtitles: embedSubtitles,
            onChanged: syncArgs
        ))
        .modifier(PostProcessChangeWatcher(
            embedThumbnail: embedThumbnail,
            embedMetadata: embedMetadata,
            sponsorBlock: sponsorBlock,
            remuxToMP4: remuxToMP4,
            extractAudio: extractAudio,
            audioFormat: audioFormat,
            audioQuality: audioQuality,
            splitByChapters: splitByChapters,
            onChanged: syncArgs
        ))
        .modifier(NetworkAuthChangeWatcher(
            proxyURL: proxyURL,
            sourceAddress: sourceAddress,
            geoBypass: geoBypass,
            cookiesBrowser: cookiesBrowser,
            username: username,
            password: password,
            onChanged: syncArgs
        ))
        .modifier(OutputChangeWatcher(
            outputTemplate: outputTemplate,
            speedLimit: speedLimit,
            noOverwrites: noOverwrites,
            writeInfoJSON: writeInfoJSON,
            writeThumbnail: writeThumbnail,
            onChanged: syncArgs
        ))
        .onAppear { syncArgs() }
    }

    // MARK: - Subtitles Section

    private var subtitlesSection: some View {
        VStack(alignment: .leading, spacing: Design.Spacing.sm) {
            Label("Subtitles", systemImage: "captions.bubble")
                .font(.caption.bold())
                .foregroundStyle(.secondary)

            Toggle("Download Subtitles", isOn: $downloadSubtitles)

            if downloadSubtitles {
                VStack(alignment: .leading, spacing: Design.Spacing.sm) {
                    Toggle("Auto-generated", isOn: $autoGeneratedSubs)

                    HStack {
                        Text("Language")
                        Spacer()
                        TextField("e.g. en,es,fr", text: $subtitleLanguage)
                            .frame(width: 120)
                            .textFieldStyle(.roundedBorder)
                            .font(.caption.monospaced())
                    }

                    HStack {
                        Text("Format")
                        Spacer()
                        Picker("", selection: $subtitleFormat) {
                            ForEach(SubtitleFormat.allCases) { fmt in
                                Text(fmt.rawValue.uppercased()).tag(fmt)
                            }
                        }
                        .frame(width: 100)
                    }

                    Toggle("Write subtitles to separate file", isOn: $writeSeparateSubtitles)
                    Toggle("Embed subtitles in video", isOn: $embedSubtitles)
                }
                .font(.caption)
                .padding(.leading, Design.Spacing.lg)
            }
        }
    }

    // MARK: - Post-Processing Section

    private var postProcessingSection: some View {
        VStack(alignment: .leading, spacing: Design.Spacing.sm) {
            Label("Post-Processing", systemImage: "wand.and.stars")
                .font(.caption.bold())
                .foregroundStyle(.secondary)

            Toggle("Embed Thumbnail", isOn: $embedThumbnail)
            Toggle("Embed Metadata", isOn: $embedMetadata)
            Toggle("SponsorBlock (remove sponsors)", isOn: $sponsorBlock)
            Toggle("Convert to MP4 after download", isOn: $remuxToMP4)
            Toggle("Extract audio only", isOn: $extractAudio)

            if extractAudio {
                VStack(alignment: .leading, spacing: Design.Spacing.sm) {
                    HStack {
                        Text("Audio Format")
                        Spacer()
                        Picker("", selection: $audioFormat) {
                            ForEach(AudioFormat.allCases) { fmt in
                                Text(fmt.rawValue.uppercased()).tag(fmt)
                            }
                        }
                        .frame(width: 100)
                    }

                    HStack {
                        Text("Audio Quality")
                        Spacer()
                        Picker("", selection: $audioQuality) {
                            ForEach(0..<10, id: \.self) { q in
                                Text(q == 0 ? "0 (best)" : q == 9 ? "9 (worst)" : "\(q)").tag(q)
                            }
                        }
                        .frame(width: 120)
                    }
                }
                .font(.caption)
                .padding(.leading, Design.Spacing.lg)
            }

            Toggle("Split by chapters", isOn: $splitByChapters)
        }
    }

    // MARK: - Network Section

    private var networkSection: some View {
        VStack(alignment: .leading, spacing: Design.Spacing.sm) {
            Label("Network", systemImage: "network")
                .font(.caption.bold())
                .foregroundStyle(.secondary)

            HStack {
                Text("Proxy URL")
                Spacer()
                TextField("socks5://127.0.0.1:1080", text: $proxyURL)
                    .frame(width: 200)
                    .textFieldStyle(.roundedBorder)
                    .font(.caption.monospaced())
            }

            HStack {
                Text("Source IP")
                Spacer()
                TextField("0.0.0.0", text: $sourceAddress)
                    .frame(width: 200)
                    .textFieldStyle(.roundedBorder)
                    .font(.caption.monospaced())
            }

            Toggle("Geo bypass", isOn: $geoBypass)
        }
    }

    // MARK: - Authentication Section

    private var authenticationSection: some View {
        VStack(alignment: .leading, spacing: Design.Spacing.sm) {
            Label("Authentication", systemImage: "lock.shield")
                .font(.caption.bold())
                .foregroundStyle(.secondary)

            HStack {
                Text("Cookies From")
                Spacer()
                Picker("", selection: $cookiesBrowser) {
                    ForEach(CookiesBrowser.allCases) { browser in
                        Text(browser.label).tag(browser)
                    }
                }
                .frame(width: 120)
            }

            HStack {
                Text("Username")
                Spacer()
                TextField("username", text: $username)
                    .frame(width: 200)
                    .textFieldStyle(.roundedBorder)
                    .font(.caption.monospaced())
            }

            HStack {
                Text("Password")
                Spacer()
                SecureField("password", text: $password)
                    .frame(width: 200)
                    .textFieldStyle(.roundedBorder)
                    .font(.caption.monospaced())
            }
        }
    }

    // MARK: - Output Section

    private var outputSection: some View {
        VStack(alignment: .leading, spacing: Design.Spacing.sm) {
            Label("Output", systemImage: "doc.badge.gearshape")
                .font(.caption.bold())
                .foregroundStyle(.secondary)

            HStack {
                Text("Output Template")
                Spacer()
                TextField("%(title)s.%(ext)s", text: $outputTemplate)
                    .frame(width: 200)
                    .textFieldStyle(.roundedBorder)
                    .font(.caption.monospaced())
            }

            HStack {
                Text("Speed Limit")
                Spacer()
                TextField("e.g. 5M", text: $speedLimit)
                    .frame(width: 80)
                    .textFieldStyle(.roundedBorder)
                    .font(.caption.monospaced())
            }

            Toggle("No overwrites", isOn: $noOverwrites)
            Toggle("Write info JSON", isOn: $writeInfoJSON)
            Toggle("Write thumbnail to file", isOn: $writeThumbnail)
        }
    }

    // MARK: - Build CLI Arguments

    private func syncArgs() {
        args = buildArgs()
    }

    private func buildArgs() -> [String] {
        var result: [String] = []

        // Subtitles
        if downloadSubtitles {
            if autoGeneratedSubs {
                result += ["--write-auto-subs"]
            } else {
                result += ["--write-subs"]
            }
            let lang = subtitleLanguage.trimmingCharacters(in: .whitespaces)
            if !lang.isEmpty {
                result += ["--sub-langs", lang]
            }
            result += ["--sub-format", subtitleFormat.rawValue]
            if writeSeparateSubtitles {
                result += ["--write-subs"]
            }
            if embedSubtitles {
                result += ["--embed-subs"]
            }
        }

        // Post-processing
        if embedThumbnail { result += ["--embed-thumbnail"] }
        if embedMetadata { result += ["--embed-metadata"] }
        if sponsorBlock { result += ["--sponsorblock-remove", "all"] }
        if remuxToMP4 { result += ["--remux-video", "mp4"] }
        if extractAudio {
            result += ["--extract-audio"]
            result += ["--audio-format", audioFormat.rawValue]
            result += ["--audio-quality", "\(audioQuality)"]
        }
        if splitByChapters { result += ["--split-chapters"] }

        // Network
        let proxy = proxyURL.trimmingCharacters(in: .whitespaces)
        if !proxy.isEmpty { result += ["--proxy", proxy] }
        let srcAddr = sourceAddress.trimmingCharacters(in: .whitespaces)
        if !srcAddr.isEmpty { result += ["--source-address", srcAddr] }
        if geoBypass { result += ["--geo-bypass"] }

        // Authentication
        if cookiesBrowser != .none {
            result += ["--cookies-from-browser", cookiesBrowser.rawValue]
        }
        let user = username.trimmingCharacters(in: .whitespaces)
        if !user.isEmpty { result += ["--username", user] }
        if !password.isEmpty { result += ["--password", password] }

        // Output
        let tmpl = outputTemplate.trimmingCharacters(in: .whitespaces)
        if !tmpl.isEmpty && tmpl != "%(title)s.%(ext)s" {
            result += ["--output", tmpl]
        }
        let limit = speedLimit.trimmingCharacters(in: .whitespaces)
        if !limit.isEmpty { result += ["--limit-rate", limit] }
        if noOverwrites { result += ["--no-overwrites"] }
        if writeInfoJSON { result += ["--write-info-json"] }
        if writeThumbnail { result += ["--write-thumbnail"] }

        return result
    }
}

// MARK: - Change Watcher Modifiers
// Split into separate ViewModifiers to avoid overwhelming the Swift type-checker.

private struct SubtitleChangeWatcher: ViewModifier {
    let downloadSubtitles: Bool
    let autoGeneratedSubs: Bool
    let subtitleLanguage: String
    let subtitleFormat: SubtitleFormat
    let writeSeparateSubtitles: Bool
    let embedSubtitles: Bool
    let onChanged: () -> Void

    func body(content: Content) -> some View {
        content
            .onChange(of: downloadSubtitles) { onChanged() }
            .onChange(of: autoGeneratedSubs) { onChanged() }
            .onChange(of: subtitleLanguage) { onChanged() }
            .onChange(of: subtitleFormat) { onChanged() }
            .onChange(of: writeSeparateSubtitles) { onChanged() }
            .onChange(of: embedSubtitles) { onChanged() }
    }
}

private struct PostProcessChangeWatcher: ViewModifier {
    let embedThumbnail: Bool
    let embedMetadata: Bool
    let sponsorBlock: Bool
    let remuxToMP4: Bool
    let extractAudio: Bool
    let audioFormat: AudioFormat
    let audioQuality: Int
    let splitByChapters: Bool
    let onChanged: () -> Void

    func body(content: Content) -> some View {
        content
            .onChange(of: embedThumbnail) { onChanged() }
            .onChange(of: embedMetadata) { onChanged() }
            .onChange(of: sponsorBlock) { onChanged() }
            .onChange(of: remuxToMP4) { onChanged() }
            .onChange(of: extractAudio) { onChanged() }
            .onChange(of: audioFormat) { onChanged() }
            .onChange(of: audioQuality) { onChanged() }
            .onChange(of: splitByChapters) { onChanged() }
    }
}

private struct NetworkAuthChangeWatcher: ViewModifier {
    let proxyURL: String
    let sourceAddress: String
    let geoBypass: Bool
    let cookiesBrowser: CookiesBrowser
    let username: String
    let password: String
    let onChanged: () -> Void

    func body(content: Content) -> some View {
        content
            .onChange(of: proxyURL) { onChanged() }
            .onChange(of: sourceAddress) { onChanged() }
            .onChange(of: geoBypass) { onChanged() }
            .onChange(of: cookiesBrowser) { onChanged() }
            .onChange(of: username) { onChanged() }
            .onChange(of: password) { onChanged() }
    }
}

private struct OutputChangeWatcher: ViewModifier {
    let outputTemplate: String
    let speedLimit: String
    let noOverwrites: Bool
    let writeInfoJSON: Bool
    let writeThumbnail: Bool
    let onChanged: () -> Void

    func body(content: Content) -> some View {
        content
            .onChange(of: outputTemplate) { onChanged() }
            .onChange(of: speedLimit) { onChanged() }
            .onChange(of: noOverwrites) { onChanged() }
            .onChange(of: writeInfoJSON) { onChanged() }
            .onChange(of: writeThumbnail) { onChanged() }
    }
}

// MARK: - Supporting Enums

enum SubtitleFormat: String, CaseIterable, Identifiable {
    case srt, vtt, ass
    var id: String { rawValue }
}

enum AudioFormat: String, CaseIterable, Identifiable {
    case mp3, m4a, wav, flac, opus
    var id: String { rawValue }
}

enum CookiesBrowser: String, CaseIterable, Identifiable {
    case none = ""
    case chrome
    case firefox
    case safari
    case edge

    var id: String { rawValue }

    var label: String {
        switch self {
        case .none: "None"
        case .chrome: "Chrome"
        case .firefox: "Firefox"
        case .safari: "Safari"
        case .edge: "Edge"
        }
    }
}
