import SwiftUI

/// Contextual subtitle/transcript options that appear when the fetched media
/// has subtitle tracks available. Builds yt-dlp CLI arguments via a binding.
struct TranscriptOptionsView: View {
    let mediaInfo: MediaInfo
    @Binding var transcriptArgs: [String]

    @State private var downloadSubtitles = false
    @State private var autoGeneratedCaptions = true
    @State private var subtitleLanguage = "en"
    @State private var subtitleFormat = SubtitleFormat.srt
    @State private var embedSubtitles = true
    @State private var saveSeparateFile = false

    private var hasSubtitles: Bool {
        !mediaInfo.subtitleLanguages.isEmpty || mediaInfo.hasAutoGeneratedCaptions
    }

    private var languageCount: Int {
        mediaInfo.availableSubtitleLanguages.count
    }

    var body: some View {
        if hasSubtitles {
            VStack(alignment: .leading, spacing: Design.Spacing.sm) {
                // Header
                HStack {
                    Label("Subtitles & Transcripts", systemImage: "captions.bubble.fill")
                        .font(.headline)
                    Spacer()
                    Text("\(languageCount) subtitle language\(languageCount == 1 ? "" : "s") available")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                        .padding(.horizontal, Design.Spacing.sm)
                        .padding(.vertical, Design.Spacing.xxs)
                        .background(.quaternary, in: Capsule())
                }

                Toggle("Download Subtitles", isOn: $downloadSubtitles)

                if downloadSubtitles {
                    VStack(alignment: .leading, spacing: Design.Spacing.sm) {
                        // Language input
                        HStack {
                            Text("Languages")
                            Spacer()
                            TextField("e.g. en,es,fr or all", text: $subtitleLanguage)
                                .frame(width: 150)
                                .textFieldStyle(.roundedBorder)
                                .font(.caption.monospaced())
                        }

                        // Format picker
                        HStack {
                            Text("Format")
                            Spacer()
                            Picker("", selection: $subtitleFormat) {
                                ForEach(SubtitleFormat.allCases) { fmt in
                                    Text(fmt.rawValue.uppercased()).tag(fmt)
                                }
                            }
                            .pickerStyle(.segmented)
                            .frame(width: 180)
                        }

                        // Auto-generated toggle
                        if mediaInfo.hasAutoGeneratedCaptions {
                            Toggle("Auto-generated captions", isOn: $autoGeneratedCaptions)
                        }

                        Toggle("Embed subtitles in video", isOn: $embedSubtitles)
                        Toggle("Save as separate file", isOn: $saveSeparateFile)
                    }
                    .font(.callout)
                    .padding(.leading, Design.Spacing.lg)
                }
            }
            .onChange(of: downloadSubtitles) { syncArgs() }
            .onChange(of: autoGeneratedCaptions) { syncArgs() }
            .onChange(of: subtitleLanguage) { syncArgs() }
            .onChange(of: subtitleFormat) { syncArgs() }
            .onChange(of: embedSubtitles) { syncArgs() }
            .onChange(of: saveSeparateFile) { syncArgs() }
            .onAppear {
                // Default auto-generated on for YouTube
                if mediaInfo.extractor.lowercased().contains("youtube") {
                    autoGeneratedCaptions = true
                }
                syncArgs()
            }
        }
    }

    // MARK: - Build CLI Arguments

    private func syncArgs() {
        var args: [String] = []
        guard downloadSubtitles else {
            transcriptArgs = args
            return
        }

        // Write subs flags
        if autoGeneratedCaptions && mediaInfo.hasAutoGeneratedCaptions {
            args.append("--write-auto-subs")
        }
        args.append("--write-subs")

        // Language
        let lang = subtitleLanguage.trimmingCharacters(in: .whitespaces)
        if !lang.isEmpty {
            args += ["--sub-langs", lang]
        }

        // Format
        args += ["--sub-format", subtitleFormat.rawValue]

        // Embed
        if embedSubtitles {
            args.append("--embed-subs")
        }

        // Separate file is the default with --write-subs; the flag is implicit.
        // If the user only wants embedded (not separate), skip --write-subs.
        // But yt-dlp needs --write-subs for --embed-subs to work, so we always include it.

        transcriptArgs = args
    }
}
